kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: random-secret-operator
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - randomsecrets.mikebryant.me.uk
  resources:
  - randomsecrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: random-secret-operator
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: random-secret-operator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: random-secret-operator
subjects:
- kind: ServiceAccount
  name: random-secret-operator
  namespace: default
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: random-secret-operator
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: random-secret-operator
    spec:
      containers:
      - image: mikebryant/random-secret-operator:0.0.1
        imagePullPolicy: IfNotPresent
        name: random-secret-operator
      serviceAccountName: random-secret-operator
